config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # login function
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  # ユーザー名による絞り込み
  scope :get_by_name, ->(name) {
  where("name like ?", "%#{name}%")
  }
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end


# ユーザー検索機能
  # def self.search(search) #ここでのself.はUser.を意味する
  #   if search
  #     where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
  #   else
  #     all #全て表示。User.は省略
  #   end
  # end
  
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザー情報をモデルから取り出す @user = User.find(params[:id])
  before_action :set_user, only: [:show, :edit, :update, :edit_basic_info, :update_basic_info, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :edit_basic_info, :update_basic_info, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :edit_basic_info, :update_basic_info, :destroy]
  before_action :admin_or_correct_user, only: [:show, :update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :show
  
  
  def index
    @users = User.paginate(page: params[:page])
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = '新規作成に成功しました。'
        redirect_to @user 
      else
        render :new
      end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    def query
      if params[:user].present? && params[:user][:name]
        User.where('name LIKE?', "%#{params[:user][:name]}%")
      else
        User.all
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f",((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>設定 ユーザー情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "Edit Basic Info") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<h1>基本情報編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user),
        local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <p><%= @user.name %></p>

      <%= f.label :department, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :department, class: "form-control" %>

      <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: "form-control" %>

      <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>
      
      <div class="center">
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
      <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>">
      キャンセル
      </button>
  </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<% if params[:name].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>全てのユーザー</h1>
<% end %>


<!--ユーザー検索機能-->
<div class=" col-md-4 col-md-offset-8">
<%= form_tag(users_path, method: "get") do %>
  <%= label_tag :name, "ユーザー名検索", class: "search-label" %>
  <div class="input-group">
  <%= text_field_tag :name, params[:name], placeholder: "キーワードを入力..." %>
  <%= submit_tag "検索", class: "btn-primary" %>
  </div>
<% end %>
</div>
<!--ユーザー検索機能 ここまで-->

<div class="col-md-10 col-md-offset-1">

  <%= will_paginate %>
  <table class="table table-condensed table-hover table-striped" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
          <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td class="center">
        <!--管理者 && 現在のユーザーではない (管理者自身は削除できない)-->
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>

</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>

<h1>ユーザー登録</h1>
  
<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <div class="row">
    <div>
      <table class="table table-bordered table-condensed" id="table-user">
        <tr>
          <td>
            <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
            【<%= l(@first_day, format: :middle) %>】時間管理表
            <%= link_to "→", user_path(date: @first_day.next_month),  class: "btn btn-info" %>
          </td>
          <td>指定勤務時間: <%= format_basic_info(@user.work_time) %></td>
          <td colspan="2">基本時間: <%= format_basic_info(@user.basic_time) %></td>
          <td>月初日: <%= l(@first_day, format: :short) %></td>
        </tr>
        
        <tr>
          <td>所属: <%= @user.department.present? ? @user.department : "未所属" %></td>
          <td>氏名: <%= @user.name %></td>
          <td>コード</td>
          <td>出勤日数: <%= @worked_sum %>日</td>
          <td>締め日: <%= l(@last_day, format: :short) %></td>
        </tr>
      </table>
      
    </div>
    
    <div>
      <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-lg btn-info" %>
    </div>
    
    <div>
      <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
        
        <thead>
          <tr>
            <th rowspan="2">日付</th>
            <th rowspan="2">曜日</th>
            <th rowspan="2">勤怠登録</th>
            <th colspan="2">出社時間</th>
            <th colspan="2">退社時間</th>
            <th rowspan="2">在社時間</th>
            <th rowspan="2">備考</th>
          </tr>
          <tr>
            <td>時</td>
            <td>分</td>
            <td>時</td>
            <td>分</td>
          </tr>
        </thead>
        
        <tbody>
          <% @attendances.each do |day| %>
          <% css_class = case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
              when '土'
                'text-primary'
              when '日'
                'text-danger'
              end %>
           <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
            <%#= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <td>
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            </td>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
            <td><%= l(day.started_at.floor_to(15.minutes), format: :minute) if day.started_at.present? %></td>
            <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
            <td><%= l(day.finished_at.floor_to(15.minutes), format: :minute) if day.finished_at.present? %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %>
            </td>
            <td><%= day.note %></td>
           </tr>
          <% end %>
        </tbody>
        
        <tfoot>
          <tr>
            <td colspan="2">
              総合勤務時間: <%= format_basic_info(@user.work_time).to_f * @worked_sum %>
            </td>
            <td colspan="5"></td>
            <td>累計在社時間: <%= format("%.2f", @total_working_times.to_f) %></td>
            <td></td>
          </tr>
        </tfoot>
        
      </table>
    </div>
  </div>
</div>